spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=Hongkong
    hikari:
      username: root
      password: 123456
      # >= 8.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定 nacos server 的地址
        server-addr: localhost:8848
        # 指定 namespace
        # namespace: 777cec93-3f26-45f3-91cd-fe61bb5352a6
        # 指定集群名称
        # 假设服务机房部署在 CD
        cluster-name: BJ
        # 设置元数据
        metadata:
          instance: content
          haha: hehe
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          # 用来指定 topic
          destination: add-bonus
          # 如果用的是 RocketMQ，一定要设置
          # 如果用的是其它 MQ，可留空
          group: binder-group

  application:
    # 服务名称尽量使用 -，不要用 _，不要用特殊字符
    name: user-center

server:
  port: 8081

# 日志
logging:
  level:
    com.alibaba.nacos: error

rocketmq:
  name-server: 127.0.0.1:9876

jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认 2 周
  expire-time-in-second: 1209600
